### ISSUE TITLE
Achieved maximum tokens but challenge not completed

### ISSUE THREAD

**Issue by howardleejh** [Proof-Of-Hack-Protocol/challenges#1]
Hi @eugenioclrc, I've completed `Challenge 4, Token` with a maximum of 21000000 tokens in my ETH wallet, but I'm not able to complete the challenge. I've verified that my ETH address does have 21000000 using `balanceOf` and `balances` methods within the smart contract instance. Am I missing something here? 

Smart Contract Instance: https://goerli.etherscan.io/address/0xff52E63712bf60C500b9033b6aCF71DAB9d5A785

using Hardhat/Ethers to run script with the following:

```
const hre = require("hardhat")
const abi = require('../abi/token.json')

async function main() {

    const provider = new hre.ethers.providers.AlchemyProvider("goerli", process.env.API_KEY)
    const victimAddr = "0xff52E63712bf60C500b9033b6aCF71DAB9d5A785"
    const victimContract = new hre.ethers.Contract(victimAddr, abi, provider)
    try {
        let balanceOf = await victimContract.balanceOf("0x1EEE5175281D43E5d46E018C5dA759D89D6B0000")
        let balances = await victimContract.balances("0x1EEE5175281D43E5d46E018C5dA759D89D6B0000")
        console.log(`balancesof: ${balanceOf} \n balances: ${balances}`)
    } catch (err) {
        return console.log(err)
    }
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
    console.error(error)
    process.exitCode = 1
})
```

and the return is:

```
balancesof: 21000000 
balances: 21000000
 ```

**Comment by howardleejh** [comment]
My bad.. The task meant to get more than the total supply. Apologies on that. I managed to pass Challenge 4.

**Comment by eugenioclrc** [comment]
Awesome!!! By the way what track is this? The etternaut? They should be
solve as the original version.
I have been a little lazy lately but i promise I will publish more
challenges

**Comment by howardleejh** [comment]
This is the Ethernaut track. Looking forward to more exciting challenges!
